-- Migration: Theme Verses for Dashboard
-- Run this after schema.sql/full_setup.sql

CREATE TABLE IF NOT EXISTS theme_verses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  verse_reference VARCHAR(120) NOT NULL,
  verse_text TEXT NOT NULL,
  translation VARCHAR(60) NOT NULL DEFAULT 'SWAHILI',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  display_weight INT UNSIGNED NOT NULL DEFAULT 1,
  start_date DATE NULL,
  end_date DATE NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_theme_verses_active (is_active),
  INDEX idx_theme_verses_dates (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO theme_verses (id, verse_reference, verse_text, translation, is_active, display_weight)
VALUES
(1, 'Zaburi 23:1', 'Bwana ndiye mchungaji wangu, sitapungukiwa na kitu.', 'SWAHILI', 1, 1),
(2, 'Yeremia 29:11', 'Mimi najua mipango niliyo nayo juu yenu, mipango ya amani na si ya mabaya.', 'SWAHILI', 1, 1),
(3, 'Wafilipi 4:13', 'Naweza kufanya mambo yote kupitia yeye anitiaye nguvu.', 'SWAHILI', 1, 1),
(4, 'Isaya 41:10', 'Usiogope, kwa maana mimi niko pamoja nawe.', 'SWAHILI', 1, 1),
(5, 'Warumi 8:28', 'Mambo yote hufanya kazi pamoja kwa wema kwa wale wampendao Mungu.', 'SWAHILI', 1, 1),
(6, 'Zaburi 46:1', 'Mungu ni kimbilio na nguvu, msaada wa karibu wakati wa shida.', 'SWAHILI', 1, 1),
(7, 'Mathayo 6:33', 'Tafuteni kwanza ufalme wa Mungu na haki yake.', 'SWAHILI', 1, 1),
(8, 'Zaburi 34:17', 'Wenye haki wanapolia, Bwana husikia na kuwaokoa.', 'SWAHILI', 1, 1),
(9, 'Yohana 14:27', 'Amani nawaachieni, amani yangu nawapa.', 'SWAHILI', 1, 1),
(10, 'Mithali 3:5', 'Mtumaini Bwana kwa moyo wako wote.', 'SWAHILI', 1, 1),
(11, 'Zaburi 121:1-2', 'Msaada wangu hutoka kwa Bwana aliyeziumba mbingu na nchi.', 'SWAHILI', 1, 1),
(12, 'Yakobo 1:5', 'Mtu akipungukiwa hekima, na amwombe Mungu.', 'SWAHILI', 1, 1),
(13, 'Waebrania 11:1', 'Imani ni hakika ya mambo yatarajiwayo.', 'SWAHILI', 1, 1),
(14, '2 Timotheo 1:7', 'Mungu hakutupa roho ya woga bali ya nguvu na upendo.', 'SWAHILI', 1, 1),
(15, 'Zaburi 37:4', 'Jifurahishe katika Bwana naye atakupa haja za moyo wako.', 'SWAHILI', 1, 1),
(16, 'Mathayo 11:28', 'Njoni kwangu ninyi wote mnaochoka, nami nitawapumzisha.', 'SWAHILI', 1, 1),
(17, 'Zaburi 119:105', 'Neno lako ni taa ya miguu yangu.', 'SWAHILI', 1, 1),
(18, 'Isaya 40:31', 'Wamngojeao Bwana watapata nguvu mpya.', 'SWAHILI', 1, 1),
(19, 'Warumi 12:2', 'Msifananishwe na dunia hii bali mgeuzwe kwa kufanywa upya akili zenu.', 'SWAHILI', 1, 1),
(20, 'Yoshua 1:9', 'Uwe hodari na moyo mkuu, Bwana yuko pamoja nawe.', 'SWAHILI', 1, 1),
(21, 'Zaburi 91:1', 'Akaaye mahali pa siri pa Aliye Juu atakaa chini ya uvuli wa Mwenyezi.', 'SWAHILI', 1, 1),
(22, 'Mathayo 7:7', 'Ombeni nanyi mtapewa, tafuteni nanyi mtaona.', 'SWAHILI', 1, 1),
(23, '1 Wakorintho 10:13', 'Mungu ni mwaminifu, hatakuacha ujaribiwe kupita uwezo wako.', 'SWAHILI', 1, 1),
(24, 'Zaburi 55:22', 'Mtwikie Bwana mzigo wako naye atakutegemeza.', 'SWAHILI', 1, 1),
(25, 'Mika 6:8', 'Tenda haki, penda rehema, tembea kwa unyenyekevu.', 'SWAHILI', 1, 1),
(26, 'Wafilipi 4:6', 'Msihangaike kwa neno lolote, bali kwa maombi.', 'SWAHILI', 1, 1),
(27, 'Zaburi 27:1', 'Bwana ni nuru yangu na wokovu wangu, nitaogopa nani?', 'SWAHILI', 1, 1),
(28, 'Waebrania 13:5', 'Sitakuacha wala sitakupungukia.', 'SWAHILI', 1, 1),
(29, 'Zaburi 118:24', 'Hii ndiyo siku aliyoifanya Bwana, tutafurahi.', 'SWAHILI', 1, 1),
(30, 'Isaya 26:3', 'Utamlinda yeye ambaye moyo wake unakutegemea.', 'SWAHILI', 1, 1),
(31, 'Zaburi 62:1', 'Roho yangu inamtumaini Mungu peke yake.', 'SWAHILI', 1, 1),
(32, 'Mathayo 5:14', 'Ninyi ni nuru ya ulimwengu.', 'SWAHILI', 1, 1),
(33, 'Warumi 15:13', 'Mungu wa tumaini awajaze furaha na amani.', 'SWAHILI', 1, 1),
(34, 'Zaburi 100:5', 'Bwana ni mwema, rehema zake ni za milele.', 'SWAHILI', 1, 1),
(35, 'Yohana 16:33', 'Ulimwenguni mtapata dhiki, lakini jipeni moyo.', 'SWAHILI', 1, 1),
(36, '2 Wakorintho 5:7', 'Tunaenenda kwa imani, si kwa kuona.', 'SWAHILI', 1, 1),
(37, 'Zaburi 16:8', 'Nimemweka Bwana mbele yangu siku zote.', 'SWAHILI', 1, 1),
(38, 'Isaya 43:2', 'Upitapo katika maji, nitakuwa pamoja nawe.', 'SWAHILI', 1, 1),
(39, 'Yakobo 4:8', 'Mkaribieni Mungu naye atawakaribia.', 'SWAHILI', 1, 1),
(40, 'Zaburi 145:18', 'Bwana yuko karibu na wote wamwitao.', 'SWAHILI', 1, 1),
(41, 'Wagalatia 6:9', 'Tusichoke kutenda mema.', 'SWAHILI', 1, 1),
(42, 'Zaburi 30:5', 'Furaha huja asubuhi.', 'SWAHILI', 1, 1),
(43, 'Mathayo 28:20', 'Niko pamoja nanyi siku zote.', 'SWAHILI', 1, 1),
(44, 'Zaburi 19:14', 'Maneno ya kinywa changu yakubalike mbele zako.', 'SWAHILI', 1, 1),
(45, 'Isaya 55:8', 'Mawazo yangu si mawazo yenu.', 'SWAHILI', 1, 1),
(46, 'Waefeso 6:10', 'Imarisheni katika Bwana.', 'SWAHILI', 1, 1),
(47, 'Zaburi 84:11', 'Bwana huwapa neema na utukufu.', 'SWAHILI', 1, 1),
(48, 'Mathayo 22:37', 'Mpende Bwana Mungu wako kwa moyo wako wote.', 'SWAHILI', 1, 1),
(49, '1 Petro 5:7', 'Mtupieni yeye fadhaa zenu zote.', 'SWAHILI', 1, 1),
(50, 'Zaburi 9:9', 'Bwana ni kimbilio wakati wa dhiki.', 'SWAHILI', 1, 1),
(51, 'Yohana 8:12', 'Mimi ndimi nuru ya ulimwengu.', 'SWAHILI', 1, 1),
(52, 'Zaburi 73:26', 'Mungu ndiye nguvu ya moyo wangu.', 'SWAHILI', 1, 1),
(53, 'Mathayo 6:34', 'Msijisumbue kwa ajili ya kesho.', 'SWAHILI', 1, 1),
(54, 'Isaya 30:21', 'Hii ndiyo njia, iendeni.', 'SWAHILI', 1, 1),
(55, 'Zaburi 18:2', 'Bwana ni mwamba wangu na ngome yangu.', 'SWAHILI', 1, 1),
(56, 'Waebrania 4:16', 'Karibieni kiti cha neema kwa ujasiri.', 'SWAHILI', 1, 1),
(57, 'Zaburi 63:3', 'Fadhili zako ni bora kuliko uhai.', 'SWAHILI', 1, 1),
(58, 'Mathayo 19:26', 'Kwa Mungu mambo yote yanawezekana.', 'SWAHILI', 1, 1),
(59, 'Warumi 5:5', 'Upendo wa Mungu umemiminwa mioyoni mwetu.', 'SWAHILI', 1, 1),
(60, 'Zaburi 86:7', 'Katika siku ya taabu nitakuita.', 'SWAHILI', 1, 1),
(61, 'Yohana 10:10', 'Nimekuja ili wawe na uzima tele.', 'SWAHILI', 1, 1),
(62, 'Zaburi 32:8', 'Nitakufundisha njia utakayokwenda.', 'SWAHILI', 1, 1),
(63, 'Mathayo 5:16', 'Nuru yenu iangaze mbele ya watu.', 'SWAHILI', 1, 1),
(64, 'Isaya 58:11', 'Bwana atakuongoza siku zote.', 'SWAHILI', 1, 1),
(65, 'Zaburi 40:1', 'Nilimngojea Bwana naye akanisikia.', 'SWAHILI', 1, 1),
(66, 'Wakolosai 3:23', 'Fanyeni yote kwa moyo kama kwa Bwana.', 'SWAHILI', 1, 1),
(67, 'Zaburi 143:8', 'Nionyeshe njia ninayopaswa kwenda.', 'SWAHILI', 1, 1),
(68, 'Mathayo 11:29', 'Jifunzeni kwangu, kwa kuwa mimi ni mpole.', 'SWAHILI', 1, 1),
(69, 'Isaya 12:2', 'Mungu ni wokovu wangu, sitaogopa.', 'SWAHILI', 1, 1),
(70, 'Zaburi 56:3', 'Nikiogopa, nitamtumaini wewe.', 'SWAHILI', 1, 1),
(71, 'Yohana 15:5', 'Bila mimi hamwezi kufanya lolote.', 'SWAHILI', 1, 1),
(72, 'Zaburi 119:11', 'Nimelificha neno lako moyoni mwangu.', 'SWAHILI', 1, 1),
(73, 'Mathayo 21:22', 'Mtakachoomba kwa imani mtapokea.', 'SWAHILI', 1, 1),
(74, 'Isaya 54:17', 'Hakuna silaha itakayofanikiwa dhidi yako.', 'SWAHILI', 1, 1),
(75, 'Zaburi 31:24', 'Jipe moyo na uwe hodari.', 'SWAHILI', 1, 1),
(76, 'Waefeso 3:20', 'Mungu anaweza kufanya zaidi ya tunavyofikiri.', 'SWAHILI', 1, 1),
(77, 'Zaburi 34:8', 'Onjeni mkaone ya kuwa Bwana ni mwema.', 'SWAHILI', 1, 1),
(78, 'Mathayo 18:20', 'Walipo wawili au watatu, mimi nipo.', 'SWAHILI', 1, 1),
(79, 'Isaya 40:29', 'Huwapa nguvu wanyonge.', 'SWAHILI', 1, 1),
(80, 'Zaburi 27:14', 'Mngojee Bwana, uwe hodari.', 'SWAHILI', 1, 1),
(81, 'Yohana 6:35', 'Mimi ndimi mkate wa uzima.', 'SWAHILI', 1, 1),
(82, 'Zaburi 125:1', 'Wamtegemeao Bwana ni kama mlima usiotikisika.', 'SWAHILI', 1, 1),
(83, 'Mathayo 10:31', 'Msihofu, ninyi ni wa thamani zaidi.', 'SWAHILI', 1, 1),
(84, 'Isaya 41:13', 'Nitakushika mkono wako wa kuume.', 'SWAHILI', 1, 1),
(85, 'Zaburi 138:3', 'Ulinipa nguvu rohoni mwangu.', 'SWAHILI', 1, 1),
(86, '2 Wathesalonike 3:3', 'Bwana ni mwaminifu atakulinda.', 'SWAHILI', 1, 1),
(87, 'Zaburi 91:2', 'Yeye ni kimbilio langu na ngome yangu.', 'SWAHILI', 1, 1),
(88, 'Mathayo 9:29', 'Na iwe kwenu kama imani yenu.', 'SWAHILI', 1, 1),
(89, 'Isaya 33:2', 'Uwe nguvu yetu kila asubuhi.', 'SWAHILI', 1, 1),
(90, 'Zaburi 20:7', 'Sisi tutalitaja jina la Bwana.', 'SWAHILI', 1, 1),
(91, 'Yohana 14:6', 'Mimi ndimi njia na kweli na uzima.', 'SWAHILI', 1, 1),
(92, 'Zaburi 28:7', 'Bwana ni nguvu yangu na ngao yangu.', 'SWAHILI', 1, 1),
(93, 'Mathayo 6:21', 'Palipo hazina yako, ndipo ulipo moyo wako.', 'SWAHILI', 1, 1),
(94, 'Isaya 26:4', 'Mtumainini Bwana milele.', 'SWAHILI', 1, 1),
(95, 'Zaburi 147:3', 'Huwaponya waliovunjika moyo.', 'SWAHILI', 1, 1),
(96, 'Yakobo 1:12', 'Heri mtu astahimiliye majaribu.', 'SWAHILI', 1, 1),
(97, 'Zaburi 33:4', 'Neno la Bwana ni la haki.', 'SWAHILI', 1, 1),
(98, 'Mathayo 5:9', 'Heri wapatanishi.', 'SWAHILI', 1, 1),
(99, 'Isaya 9:6', 'Ataitwa Mfalme wa amani.', 'SWAHILI', 1, 1),
(100, 'Zaburi 150:6', 'Kila mwenye pumzi na amsifu Bwana.', 'SWAHILI', 1, 1)
ON DUPLICATE KEY UPDATE
  verse_reference = VALUES(verse_reference),
  verse_text = VALUES(verse_text),
  translation = VALUES(translation),
  is_active = VALUES(is_active),
  display_weight = VALUES(display_weight);
